@UnitOfWork_HostAddress = http://localhost:5045

### Get All Employees
GET {{UnitOfWork_HostAddress}}/api/Employee/GetAllEmployees
Accept: application/json

### Get Employee By Id
GET {{UnitOfWork_HostAddress}}/api/Employee/GetEmployeeById/5
Accept: application/json

###
